### PR TITLE
Rb version bump and rbenv instructions

### PR DESCRIPTION
**Pull request by tlehman**

### CODE REVIEW

**Comment by therubymug** [comment]
@tlehman do you mind adding 2.2.1 to the travisci.yml? I think that belongs in the pull request.

**Comment by therubymug** [comment]
Thanks @tlehman!

**Comment by tlehman** [comment]
Did you mean to merge this?

**Comment by therubymug** [comment]
It is merged.

**Comment by tlehman** [comment]
Oh, nevermind then

**Pull request closed without merging**
